version: "3.6"
services:
  scribe:
    # build:
    #   context: ./src
    #   dockerfile: ./Dockerfile
    image: ergrassa/mood-scribe:latest
    env_file:
      - ./.env
    ports:
      - "80"
    command: bash ./mood/startapp.sh