name: Build and push to DH
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    server-build:
        name: Server Build
        runs-on: ubuntu-latest
        environment: "313"
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: ./src
                  file: ./src/Dockerfile
                  push: true
                  tags: ergrassa/mood-scribe:latest